FROM ruby:3.0-alpine

RUN mkdir -p /app/vendor/cache
WORKDIR /app

# RUN bootstrap node
RUN apk --update add git libpq libxslt tzdata less

RUN apk --update add --virtual build_deps \
    build-base libc-dev linux-headers \
    openssl-dev libxml2-dev libxslt-dev postgresql-dev

# add Gemfile & install dependencies
ADD Gemfile* /app/
ADD vendor/cache /app/vendor/cache

RUN bundle install --jobs=8 --retry=3

# add application code
COPY . /app
